GET http://localhost:3000/lebenslauf


###


PATCH http://localhost:3000/api/0
Content-Type: application/json

{
    "ident": "0",
    "values": [
        {"location": "intro.items.0.title", "value": "Blub"},
        {"location": "intro.items.0.content", "value": "Blubbel"}
    ]
}

###


POST http://martin-richter.me:3000/lebenslauf/admin/login
Content-Type: application/json

{
    "username": "martin",
    "password": "Blabla12"
}

