GET http://localhost:3000/lebenslauf


###


GET http://martin-richter.me:3000/lebenslauf/admin/users


###

POST http://martin-richter.me:3000/lebenslauf/admin/createDefault

{}


###

DELETE http://martin-richter.me:3000/lebenslauf/admin/deleteDefault



###

GET http://martin-richter.me:3000/lebenslauf