GET http://localhost:3000/lebenslauf


###


GET http://localhost:3000/lebenslauf/admin/users


###


POST http://localhost:3000/lebenslauf/admin/login
Content-Type: application/json

{
    "username": "martin",
    "password": "Blabla12"
}


###

POST http://localhost:3000/lebenslauf/admin/createDefault

{}


###

DELETE http://localhost:3000/lebenslauf/admin/deleteDefault



###


GET http://martin-richter.me:3000/lebenslauf/admin/users


###

POST http://martin-richter.me:3000/lebenslauf/admin/createDefault

{}


###

DELETE http://martin-richter.me:3000/lebenslauf/admin/deleteDefault



###

GET http://martin-richter.me:3000/lebenslauf